export interface District {
  name: string
  zipCode: string
}

export interface ProvinceData {
  districts: District[]
}

export const THAILAND_ADDRESS: Record<string, ProvinceData> = {
  "กรุงเทพมหานคร": {
    districts: [
      { name: "พระนคร", zipCode: "10200" },
      { name: "ดุสิต", zipCode: "10300" },
      { name: "หนองจอก", zipCode: "10530" },
      { name: "บางรัก", zipCode: "10500" },
      { name: "บางเขน", zipCode: "10220" },
      { name: "บางกอกน้อย", zipCode: "10700" },
      { name: "บางขุนเทียน", zipCode: "10150" },
      { name: "ภาษีเจริญ", zipCode: "10160" },
      { name: "หนองแขม", zipCode: "10160" },
      { name: "ราษฎร์บูรณะ", zipCode: "10140" },
      { name: "หลักสี่", zipCode: "10210" },
      { name: "ลาดกระบัง", zipCode: "10520" },
      { name: "ยานนาวา", zipCode: "10120" },
      { name: "สัมพันธวงศ์", zipCode: "10100" },
      { name: "พระโขนง", zipCode: "10260" },
      { name: "มีนบุรี", zipCode: "10510" },
      { name: "ลาดพร้าว", zipCode: "10230" },
      { name: "วังทองหลาง", zipCode: "10310" },
      { name: "คลองสาน", zipCode: "10600" },
      { name: "ตลิ่งชัน", zipCode: "10170" },
      { name: "บางกอกใหญ่", zipCode: "10600" },
      { name: "ห้วยขวาง", zipCode: "10310" },
      { name: "คลองเตย", zipCode: "10110" },
      { name: "วัฒนา", zipCode: "10110" },
      { name: "บางแค", zipCode: "10160" },
      { name: "หลักสี่", zipCode: "10210" },
      { name: "ดอนเมือง", zipCode: "10210" },
      { name: "ราษฎร์บูรณะ", zipCode: "10140" },
      { name: "หลักสี่", zipCode: "10210" },
      { name: "ลาดกระบัง", zipCode: "10520" },
      { name: "จตุจักร", zipCode: "10900" },
      { name: "บึงกุ่ม", zipCode: "10240" },
      { name: "สาทร", zipCode: "10120" },
      { name: "บางซื่อ", zipCode: "10800" },
      { name: "จอมทอง", zipCode: "10150" },
      { name: "ดินแดง", zipCode: "10400" },
      { name: "บึงกุ่ม", zipCode: "10240" },
      { name: "บางนา", zipCode: "10260" },
      { name: "ทวีวัฒนา", zipCode: "10170" },
      { name: "ทุ่งครุ", zipCode: "10140" },
      { name: "บางบอน", zipCode: "10150" },
      { name: "ประเวศ", zipCode: "10250" },
      { name: "คันนายาว", zipCode: "10230" },
      { name: "สาธร", zipCode: "10120" },
      { name: "บางพลัด", zipCode: "10700" },
      { name: "บางกอกน้อย", zipCode: "10700" },
      { name: "สวนหลวง", zipCode: "10250" },
      { name: "คลองสาน", zipCode: "10600" },
      { name: "มีนบุรี", zipCode: "10510" },
      { name: "สะพานสูง", zipCode: "10240" },
      { name: "คลองสาน", zipCode: "10600" },
    ],
  },
  "เชียงใหม่": {
    districts: [
      { name: "เมืองเชียงใหม่", zipCode: "50000" },
      { name: "จอมทอง", zipCode: "50160" },
      { name: "แม่แจ่ม", zipCode: "50270" },
      { name: "เชียงดาว", zipCode: "50170" },
      { name: "ดอยสะเก็ด", zipCode: "50220" },
      { name: "แม่แตง", zipCode: "50150" },
      { name: "แม่ริม", zipCode: "50180" },
      { name: "สะเมิง", zipCode: "50250" },
      { name: "ฝาง", zipCode: "50110" },
      { name: "แม่อาย", zipCode: "50280" },
      { name: "พร้าว", zipCode: "50190" },
      { name: "สันป่าตอง", zipCode: "50120" },
      { name: "สันกำแพง", zipCode: "50130" },
      { name: "สันทราย", zipCode: "50210" },
      { name: "หางดง", zipCode: "50230" },
      { name: "ฮอด", zipCode: "50240" },
      { name: "ดอยเต่า", zipCode: "50260" },
      { name: "อมก๋อย", zipCode: "50310" },
      { name: "สารภี", zipCode: "50140" },
      { name: "เวียงแหง", zipCode: "50350" },
      { name: "ไชยปราการ", zipCode: "50320" },
      { name: "แม่วาง", zipCode: "50360" },
      { name: "แม่ออน", zipCode: "50130" },
      { name: "ดอยหล่อ", zipCode: "50160" },
      { name: "กัลยาณิวัฒนา", zipCode: "58130" },
    ],
  },
  "เชียงราย": {
    districts: [
      { name: "เมืองเชียงราย", zipCode: "57000" },
      { name: "เวียงชัย", zipCode: "57210" },
      { name: "เชียงของ", zipCode: "57140" },
      { name: "เทิง", zipCode: "57160" },
      { name: "พาน", zipCode: "57120" },
      { name: "ป่าแดด", zipCode: "57190" },
      { name: "แม่จัน", zipCode: "57110" },
      { name: "เชียงแสน", zipCode: "57150" },
      { name: "แม่สาย", zipCode: "57130" },
      { name: "แม่สรวย", zipCode: "57180" },
      { name: "เวียงป่าเป้า", zipCode: "57170" },
      { name: "พญาเม็งราย", zipCode: "57290" },
      { name: "เวียงแก่น", zipCode: "57310" },
      { name: "ขุนตาล", zipCode: "57340" },
      { name: "แม่ฟ้าหลวง", zipCode: "57240" },
      { name: "แม่ลาว", zipCode: "57250" },
      { name: "เวียงเชียงรุ้ง", zipCode: "57210" },
      { name: "ดอยหลวง", zipCode: "57110" },
    ],
  },
  "ลำปาง": {
    districts: [
      { name: "เมืองลำปาง", zipCode: "52000" },
      { name: "แม่เมาะ", zipCode: "52220" },
      { name: "เกาะคา", zipCode: "52130" },
      { name: "เสริมงาม", zipCode: "52210" },
      { name: "งาว", zipCode: "52110" },
      { name: "แจ้ห่ม", zipCode: "52120" },
      { name: "วังเหนือ", zipCode: "52140" },
      { name: "เถิน", zipCode: "52160" },
      { name: "แม่พริก", zipCode: "52180" },
      { name: "แม่ทะ", zipCode: "52150" },
      { name: "สบปราบ", zipCode: "52170" },
      { name: "ห้างฉัตร", zipCode: "52190" },
      { name: "เมืองปาน", zipCode: "52240" },
    ],
  },
  "ลำพูน": {
    districts: [
      { name: "เมืองลำพูน", zipCode: "51000" },
      { name: "แม่ทา", zipCode: "51140" },
      { name: "บ้านโฮ่ง", zipCode: "51130" },
      { name: "ลี้", zipCode: "51110" },
      { name: "ทุ่งหัวช้าง", zipCode: "51160" },
      { name: "ป่าซาง", zipCode: "51120" },
      { name: "บ้านธิ", zipCode: "51180" },
      { name: "เวียงหนองล่อง", zipCode: "51120" },
    ],
  },
  "แม่ฮ่องสอน": {
    districts: [
      { name: "เมืองแม่ฮ่องสอน", zipCode: "58000" },
      { name: "ขุนยวม", zipCode: "58140" },
      { name: "ปาย", zipCode: "58130" },
      { name: "แม่สะเรียง", zipCode: "58110" },
      { name: "แม่ลาน้อย", zipCode: "58120" },
      { name: "สบเมย", zipCode: "58110" },
      { name: "ปางมะผ้า", zipCode: "58150" },
    ],
  },
  "น่าน": {
    districts: [
      { name: "เมืองน่าน", zipCode: "55000" },
      { name: "แม่จริม", zipCode: "55170" },
      { name: "บ้านหลวง", zipCode: "55190" },
      { name: "นาน้อย", zipCode: "55150" },
      { name: "ปัว", zipCode: "55120" },
      { name: "ท่าวังผา", zipCode: "55140" },
      { name: "เวียงสา", zipCode: "55110" },
      { name: "ทุ่งช้าง", zipCode: "55130" },
      { name: "เชียงกลาง", zipCode: "55160" },
      { name: "นาหมื่น", zipCode: "55180" },
      { name: "สันติสุข", zipCode: "55210" },
      { name: "บึงโขงหลง", zipCode: "38220" },
      { name: "ภูเพียง", zipCode: "55000" },
    ],
  },
  "พะเยา": {
    districts: [
      { name: "เมืองพะเยา", zipCode: "56000" },
      { name: "จุน", zipCode: "56150" },
      { name: "เชียงคำ", zipCode: "56110" },
      { name: "เชียงม่วน", zipCode: "56160" },
      { name: "ดอกคำใต้", zipCode: "56120" },
      { name: "ปง", zipCode: "56140" },
      { name: "แม่ใจ", zipCode: "56130" },
      { name: "ภูซาง", zipCode: "56110" },
      { name: "ภูกามยาว", zipCode: "56000" },
    ],
  },
  "แพร่": {
    districts: [
      { name: "เมืองแพร่", zipCode: "54000" },
      { name: "ร้องกวาง", zipCode: "54140" },
      { name: "ลอง", zipCode: "54150" },
      { name: "สูงเม่น", zipCode: "54130" },
      { name: "เด่นชัย", zipCode: "54110" },
      { name: "สอง", zipCode: "54120" },
      { name: "วังชิ้น", zipCode: "54160" },
      { name: "หนองม่วงไข่", zipCode: "54170" },
    ],
  },
  "อุตรดิตถ์": {
    districts: [
      { name: "เมืองอุตรดิตถ์", zipCode: "53000" },
      { name: "ตรอน", zipCode: "53140" },
      { name: "ท่าปลา", zipCode: "53150" },
      { name: "น้ำปาด", zipCode: "53110" },
      { name: "ฟากท่า", zipCode: "53160" },
      { name: "บ้านโคก", zipCode: "53180" },
      { name: "พิชัย", zipCode: "53120" },
      { name: "ลับแล", zipCode: "53130" },
      { name: "ทองแสนขัน", zipCode: "53230" },
    ],
  },
  "ตาก": {
    districts: [
      { name: "เมืองตาก", zipCode: "63000" },
      { name: "บ้านตาก", zipCode: "63120" },
      { name: "สามเงา", zipCode: "63130" },
      { name: "แม่ระมาด", zipCode: "63140" },
      { name: "ท่าสองยาง", zipCode: "63150" },
      { name: "แม่สอด", zipCode: "63110" },
      { name: "พบพระ", zipCode: "63160" },
      { name: "อุ้มผาง", zipCode: "63170" },
      { name: "วังเจ้า", zipCode: "63000" },
    ],
  },
  "สุโขทัย": {
    districts: [
      { name: "เมืองสุโขทัย", zipCode: "64000" },
      { name: "บ้านด่านลานหอย", zipCode: "64140" },
      { name: "คีรีมาศ", zipCode: "64160" },
      { name: "กงไกรลาศ", zipCode: "64170" },
      { name: "ศรีสัชนาลัย", zipCode: "64130" },
      { name: "ศรีสำโรง", zipCode: "64120" },
      { name: "สวรรคโลก", zipCode: "64110" },
      { name: "ศรีนคร", zipCode: "64180" },
      { name: "ทุ่งเสลี่ยม", zipCode: "64150" },
    ],
  },
  "กำแพงเพชร": {
    districts: [
      { name: "เมืองกำแพงเพชร", zipCode: "62000" },
      { name: "ไทรงาม", zipCode: "62150" },
      { name: "คลองลาน", zipCode: "62180" },
      { name: "ขาณุวรลักษบุรี", zipCode: "62130" },
      { name: "คลองขลุง", zipCode: "62120" },
      { name: "พรานกระต่าย", zipCode: "62110" },
      { name: "ลานกระบือ", zipCode: "62170" },
      { name: "ทรายทองวัฒนา", zipCode: "62190" },
      { name: "ปางศิลาทอง", zipCode: "62120" },
      { name: "บึงสามัคคี", zipCode: "62210" },
      { name: "โกสัมพีนคร", zipCode: "62000" },
    ],
  },
  "พิษณุโลก": {
    districts: [
      { name: "เมืองพิษณุโลก", zipCode: "65000" },
      { name: "นครไทย", zipCode: "65120" },
      { name: "ชาติตระการ", zipCode: "65170" },
      { name: "บางระกำ", zipCode: "65140" },
      { name: "บางกระทุ่ม", zipCode: "65110" },
      { name: "พรหมพิราม", zipCode: "65150" },
      { name: "วัดโบสถ์", zipCode: "65160" },
      { name: "วังทอง", zipCode: "65130" },
      { name: "เนินมะปราง", zipCode: "65190" },
    ],
  },
  "พิจิตร": {
    districts: [
      { name: "เมืองพิจิตร", zipCode: "66000" },
      { name: "วังทรายพูน", zipCode: "66180" },
      { name: "โพธิ์ประทับช้าง", zipCode: "66190" },
      { name: "ตะพานหิน", zipCode: "66110" },
      { name: "บางมูลนาก", zipCode: "66120" },
      { name: "โพทะเล", zipCode: "66130" },
      { name: "สามง่าม", zipCode: "66140" },
      { name: "ทับคล้อ", zipCode: "66150" },
      { name: "สากเหล็ก", zipCode: "66160" },
      { name: "บึงนาราง", zipCode: "66130" },
      { name: "ดงเจริญ", zipCode: "66210" },
      { name: "วชิรบารมี", zipCode: "66140" },
    ],
  },
  "เพชรบูรณ์": {
    districts: [
      { name: "เมืองเพชรบูรณ์", zipCode: "67000" },
      { name: "ชนแดน", zipCode: "67150" },
      { name: "หล่มสัก", zipCode: "67110" },
      { name: "หล่มเก่า", zipCode: "67120" },
      { name: "วิเชียรบุรี", zipCode: "67130" },
      { name: "ศรีเทพ", zipCode: "67170" },
      { name: "หนองไผ่", zipCode: "67140" },
      { name: "บึงสามพัน", zipCode: "67160" },
      { name: "น้ำหนาว", zipCode: "67260" },
      { name: "วังโป่ง", zipCode: "67240" },
      { name: "เขาค้อ", zipCode: "67270" },
    ],
  },
  "นครสวรรค์": {
    districts: [
      { name: "เมืองนครสวรรค์", zipCode: "60000" },
      { name: "โกรกพระ", zipCode: "60170" },
      { name: "ชุมแสง", zipCode: "60120" },
      { name: "หนองบัว", zipCode: "60110" },
      { name: "บรรพตพิสัย", zipCode: "60180" },
      { name: "เก้าเลี้ยว", zipCode: "60230" },
      { name: "ตาคลี", zipCode: "60140" },
      { name: "ท่าตะโก", zipCode: "60160" },
      { name: "ไพศาลี", zipCode: "60220" },
      { name: "พยุหะคีรี", zipCode: "60130" },
      { name: "ลาดยาว", zipCode: "60150" },
      { name: "ตากฟ้า", zipCode: "60190" },
      { name: "แม่วงก์", zipCode: "60150" },
      { name: "แม่เปิน", zipCode: "60150" },
      { name: "ชุมตาบง", zipCode: "60150" },
    ],
  },
  "อุทัยธานี": {
    districts: [
      { name: "เมืองอุทัยธานี", zipCode: "61000" },
      { name: "ทัพทัน", zipCode: "61120" },
      { name: "สว่างอารมณ์", zipCode: "61150" },
      { name: "หนองฉาง", zipCode: "61110" },
      { name: "หนองขาหย่าง", zipCode: "61130" },
      { name: "บ้านไร่", zipCode: "61140" },
      { name: "ลานสัก", zipCode: "61160" },
      { name: "ห้วยคต", zipCode: "61170" },
    ],
  },
  "ชัยนาท": {
    districts: [
      { name: "เมืองชัยนาท", zipCode: "17000" },
      { name: "มโนรมย์", zipCode: "17110" },
      { name: "วัดสิงห์", zipCode: "17120" },
      { name: "สรรพยา", zipCode: "17150" },
      { name: "สรรคบุรี", zipCode: "17140" },
      { name: "หันคา", zipCode: "17130" },
      { name: "หนองมะโมง", zipCode: "17120" },
      { name: "เนินขาม", zipCode: "17130" },
    ],
  },
  "สิงห์บุรี": {
    districts: [
      { name: "เมืองสิงห์บุรี", zipCode: "16000" },
      { name: "บางระจัน", zipCode: "16130" },
      { name: "ค่ายบางระจัน", zipCode: "16150" },
      { name: "พรหมบุรี", zipCode: "16120" },
      { name: "ท่าช้าง", zipCode: "16140" },
      { name: "อินทร์บุรี", zipCode: "16110" },
    ],
  },
  "อ่างทอง": {
    districts: [
      { name: "เมืองอ่างทอง", zipCode: "14000" },
      { name: "ไชโย", zipCode: "14140" },
      { name: "ป่าโมก", zipCode: "14130" },
      { name: "โพธิ์ทอง", zipCode: "14120" },
      { name: "แสวงหา", zipCode: "14150" },
      { name: "วิเศษชัยชาญ", zipCode: "14110" },
      { name: "สามโก้", zipCode: "14160" },
    ],
  },
  "ลพบุรี": {
    districts: [
      { name: "เมืองลพบุรี", zipCode: "15000" },
      { name: "พัฒนานิคม", zipCode: "15140" },
      { name: "โคกสำโรง", zipCode: "15120" },
      { name: "ชัยบาดาล", zipCode: "15130" },
      { name: "ท่าวุ้ง", zipCode: "15150" },
      { name: "บ้านหมี่", zipCode: "15110" },
      { name: "ท่าหลวง", zipCode: "15230" },
      { name: "สระโบสถ์", zipCode: "15240" },
      { name: "โคกเจริญ", zipCode: "15250" },
      { name: "ลำสนธิ", zipCode: "15190" },
      { name: "หนองม่วง", zipCode: "15170" },
    ],
  },
  "สระบุรี": {
    districts: [
      { name: "เมืองสระบุรี", zipCode: "18000" },
      { name: "แก่งคอย", zipCode: "18110" },
      { name: "หนองแค", zipCode: "18140" },
      { name: "วิหารแดง", zipCode: "18150" },
      { name: "หนองแซง", zipCode: "18170" },
      { name: "บ้านหมอ", zipCode: "18130" },
      { name: "ดอนพุด", zipCode: "18210" },
      { name: "หนองโดน", zipCode: "18190" },
      { name: "พระพุทธบาท", zipCode: "18120" },
      { name: "เสาไห้", zipCode: "18160" },
      { name: "มวกเหล็ก", zipCode: "18180" },
      { name: "วังม่วง", zipCode: "18220" },
      { name: "เฉลิมพระเกียรติ", zipCode: "18000" },
    ],
  },
  "นครนายก": {
    districts: [
      { name: "เมืองนครนายก", zipCode: "26000" },
      { name: "ปากพลี", zipCode: "26130" },
      { name: "บ้านนา", zipCode: "26110" },
      { name: "องครักษ์", zipCode: "26120" },
    ],
  },
  "ปราจีนบุรี": {
    districts: [
      { name: "เมืองปราจีนบุรี", zipCode: "25000" },
      { name: "กบินทร์บุรี", zipCode: "25110" },
      { name: "นาดี", zipCode: "25220" },
      { name: "บ้านสร้าง", zipCode: "25150" },
      { name: "ประจันตคาม", zipCode: "25130" },
      { name: "ศรีมหาโพธิ", zipCode: "25140" },
      { name: "ศรีมโหสถ", zipCode: "25190" },
    ],
  },
  "สระแก้ว": {
    districts: [
      { name: "เมืองสระแก้ว", zipCode: "27000" },
      { name: "คลองหาด", zipCode: "27260" },
      { name: "ตาพระยา", zipCode: "27180" },
      { name: "วังน้ำเย็น", zipCode: "27210" },
      { name: "เขาฉกรรจ์", zipCode: "27000" },
      { name: "โคกสูง", zipCode: "27120" },
      { name: "วัฒนานคร", zipCode: "27160" },
      { name: "อรัญประเทศ", zipCode: "27120" },
      { name: "เขาฉกรรจ์", zipCode: "27000" },
    ],
  },
  "นนทบุรี": {
    districts: [
      { name: "เมืองนนทบุรี", zipCode: "11000" },
      { name: "บางกรวย", zipCode: "11130" },
      { name: "บางใหญ่", zipCode: "11140" },
      { name: "บางบัวทอง", zipCode: "11110" },
      { name: "ไทรน้อย", zipCode: "11150" },
      { name: "ปากเกร็ด", zipCode: "11120" },
    ],
  },
  "ปทุมธานี": {
    districts: [
      { name: "เมืองปทุมธานี", zipCode: "12000" },
      { name: "คลองหลวง", zipCode: "12120" },
      { name: "ธัญบุรี", zipCode: "12110" },
      { name: "หนองเสือ", zipCode: "12170" },
      { name: "ลาดหลุมแก้ว", zipCode: "12140" },
      { name: "ลำลูกกา", zipCode: "12150" },
      { name: "สามโคก", zipCode: "12160" },
    ],
  },
  "พระนครศรีอยุธยา": {
    districts: [
      { name: "พระนครศรีอยุธยา", zipCode: "13000" },
      { name: "ท่าเรือ", zipCode: "13130" },
      { name: "นครหลวง", zipCode: "13260" },
      { name: "บางไทร", zipCode: "13190" },
      { name: "บางบาล", zipCode: "13250" },
      { name: "บางปะอิน", zipCode: "13160" },
      { name: "บางปะหัน", zipCode: "13220" },
      { name: "ผักไห่", zipCode: "13120" },
      { name: "ภาชี", zipCode: "13140" },
      { name: "ลาดบัวหลวง", zipCode: "13230" },
      { name: "วังน้อย", zipCode: "13170" },
      { name: "เสนา", zipCode: "13110" },
      { name: "บางซ้าย", zipCode: "13270" },
      { name: "อุทัย", zipCode: "13210" },
      { name: "มหาราช", zipCode: "13150" },
      { name: "บ้านแพรก", zipCode: "13240" },
    ],
  },
  "สมุทรปราการ": {
    districts: [
      { name: "เมืองสมุทรปราการ", zipCode: "10270" },
      { name: "บางบ่อ", zipCode: "10550" },
      { name: "บางพลี", zipCode: "10540" },
      { name: "พระประแดง", zipCode: "10130" },
      { name: "พระสมุทรเจดีย์", zipCode: "10290" },
      { name: "บางเสาธง", zipCode: "10570" },
    ],
  },
  "สมุทรสาคร": {
    districts: [
      { name: "เมืองสมุทรสาคร", zipCode: "74000" },
      { name: "กระทุ่มแบน", zipCode: "74110" },
      { name: "บ้านแพ้ว", zipCode: "74120" },
    ],
  },
  "สมุทรสงคราม": {
    districts: [
      { name: "เมืองสมุทรสงคราม", zipCode: "75000" },
      { name: "บางคนที", zipCode: "75120" },
      { name: "อัมพวา", zipCode: "75110" },
    ],
  },
  "นครปฐม": {
    districts: [
      { name: "เมืองนครปฐม", zipCode: "73000" },
      { name: "กำแพงแสน", zipCode: "73140" },
      { name: "นครชัยศรี", zipCode: "73120" },
      { name: "ดอนตูม", zipCode: "73150" },
      { name: "บางเลน", zipCode: "73130" },
      { name: "สามพราน", zipCode: "73110" },
      { name: "พุทธมณฑล", zipCode: "73170" },
    ],
  },
  "สุพรรณบุรี": {
    districts: [
      { name: "เมืองสุพรรณบุรี", zipCode: "72000" },
      { name: "เดิมบางนางบวช", zipCode: "72120" },
      { name: "ด่านช้าง", zipCode: "72180" },
      { name: "บางปลาม้า", zipCode: "72150" },
      { name: "ศรีประจันต์", zipCode: "72140" },
      { name: "ดอนเจดีย์", zipCode: "72170" },
      { name: "สองพี่น้อง", zipCode: "72110" },
      { name: "สามชุก", zipCode: "72130" },
      { name: "อู่ทอง", zipCode: "72160" },
      { name: "หนองหญ้าไซ", zipCode: "72240" },
    ],
  },
  "กาญจนบุรี": {
    districts: [
      { name: "เมืองกาญจนบุรี", zipCode: "71000" },
      { name: "ไทรโยค", zipCode: "71150" },
      { name: "บ่อพลอย", zipCode: "71160" },
      { name: "ศรีสวัสดิ์", zipCode: "71250" },
      { name: "ท่ามะกา", zipCode: "71120" },
      { name: "ท่าม่วง", zipCode: "71110" },
      { name: "ทองผาภูมิ", zipCode: "71180" },
      { name: "สังขละบุรี", zipCode: "71240" },
      { name: "พนมทวน", zipCode: "71140" },
      { name: "เลาขวัญ", zipCode: "71210" },
      { name: "ด่านมะขามเตี้ย", zipCode: "71260" },
      { name: "หนองปรือ", zipCode: "71220" },
      { name: "ห้วยกระเจา", zipCode: "71170" },
    ],
  },
  "ราชบุรี": {
    districts: [
      { name: "เมืองราชบุรี", zipCode: "70000" },
      { name: "จอมบึง", zipCode: "70150" },
      { name: "สวนผึ้ง", zipCode: "70180" },
      { name: "ดำเนินสะดวก", zipCode: "70130" },
      { name: "บ้านโป่ง", zipCode: "70110" },
      { name: "บางแพ", zipCode: "70160" },
      { name: "โพธาราม", zipCode: "70120" },
      { name: "ปากท่อ", zipCode: "70140" },
      { name: "วัดเพลง", zipCode: "70170" },
      { name: "บ้านคา", zipCode: "70180" },
    ],
  },
  "เพชรบุรี": {
    districts: [
      { name: "เมืองเพชรบุรี", zipCode: "76000" },
      { name: "เขาย้อย", zipCode: "76140" },
      { name: "หนองหญ้าปล้อง", zipCode: "76160" },
      { name: "ชะอำ", zipCode: "76120" },
      { name: "ท่ายาง", zipCode: "76130" },
      { name: "บ้านลาด", zipCode: "76150" },
      { name: "บ้านแหลม", zipCode: "76110" },
      { name: "แก่งกระจาน", zipCode: "76170" },
    ],
  },
  "ประจวบคีรีขันธ์": {
    districts: [
      { name: "เมืองประจวบคีรีขันธ์", zipCode: "77000" },
      { name: "กุยบุรี", zipCode: "77150" },
      { name: "ทับสะแก", zipCode: "77130" },
      { name: "บางสะพาน", zipCode: "77140" },
      { name: "บางสะพานน้อย", zipCode: "77170" },
      { name: "ปราณบุรี", zipCode: "77120" },
      { name: "หัวหิน", zipCode: "77110" },
      { name: "สามร้อยยอด", zipCode: "77180" },
    ],
  },
  "ชลบุรี": {
    districts: [
      { name: "เมืองชลบุรี", zipCode: "20000" },
      { name: "บ้านบึง", zipCode: "20170" },
      { name: "หนองใหญ่", zipCode: "20190" },
      { name: "บางละมุง", zipCode: "20150" },
      { name: "พานทอง", zipCode: "20160" },
      { name: "พนัสนิคม", zipCode: "20140" },
      { name: "ศรีราชา", zipCode: "20110" },
      { name: "เกาะสีชัง", zipCode: "20120" },
      { name: "สัตหีบ", zipCode: "20180" },
      { name: "บ่อทอง", zipCode: "20270" },
      { name: "เกาะจันทร์", zipCode: "20240" },
    ],
  },
  "ระยอง": {
    districts: [
      { name: "เมืองระยอง", zipCode: "21000" },
      { name: "บ้านฉาง", zipCode: "21130" },
      { name: "แกลง", zipCode: "21110" },
      { name: "วังจันทร์", zipCode: "21210" },
      { name: "บ้านค่าย", zipCode: "21120" },
      { name: "ปลวกแดง", zipCode: "21140" },
      { name: "เขาชะเมา", zipCode: "21110" },
      { name: "นิคมพัฒนา", zipCode: "21180" },
    ],
  },
  "จันทบุรี": {
    districts: [
      { name: "เมืองจันทบุรี", zipCode: "22000" },
      { name: "ขลุง", zipCode: "22110" },
      { name: "ท่าใหม่", zipCode: "22120" },
      { name: "โป่งน้ำร้อน", zipCode: "22150" },
      { name: "มะขาม", zipCode: "22150" },
      { name: "แหลมสิงห์", zipCode: "22130" },
      { name: "สอยดาว", zipCode: "22180" },
      { name: "แก่งหางแมว", zipCode: "22160" },
      { name: "นายายอาม", zipCode: "22160" },
      { name: "เขาคิชฌกูฏ", zipCode: "22210" },
    ],
  },
  "ตราด": {
    districts: [
      { name: "เมืองตราด", zipCode: "23000" },
      { name: "คลองใหญ่", zipCode: "23110" },
      { name: "เขาสมิง", zipCode: "23130" },
      { name: "บ่อไร่", zipCode: "23140" },
      { name: "แหลมงอบ", zipCode: "23120" },
      { name: "เกาะกูด", zipCode: "23000" },
      { name: "เกาะช้าง", zipCode: "23170" },
    ],
  },
  "ฉะเชิงเทรา": {
    districts: [
      { name: "เมืองฉะเชิงเทรา", zipCode: "24000" },
      { name: "บางคล้า", zipCode: "24110" },
      { name: "บางน้ำเปรี้ยว", zipCode: "24150" },
      { name: "บางปะกง", zipCode: "24130" },
      { name: "บ้านโพธิ์", zipCode: "24140" },
      { name: "พนมสารคาม", zipCode: "24120" },
      { name: "ราชสาส์น", zipCode: "24120" },
      { name: "สนามชัยเขต", zipCode: "24160" },
      { name: "แปลงยาว", zipCode: "24190" },
      { name: "ท่าตะเกียบ", zipCode: "24160" },
      { name: "คลองเขื่อน", zipCode: "24000" },
    ],
  },
  "นครราชสีมา": {
    districts: [
      { name: "เมืองนครราชสีมา", zipCode: "30000" },
      { name: "ครบุรี", zipCode: "30250" },
      { name: "เสิงสาง", zipCode: "30330" },
      { name: "คง", zipCode: "30260" },
      { name: "บ้านเหลื่อม", zipCode: "30350" },
      { name: "จักราช", zipCode: "30230" },
      { name: "โชคชัย", zipCode: "30190" },
      { name: "ด่านขุนทด", zipCode: "30210" },
      { name: "โนนไทย", zipCode: "30220" },
      { name: "โนนสูง", zipCode: "30160" },
      { name: "ขามสะแกแสง", zipCode: "30290" },
      { name: "บัวใหญ่", zipCode: "30120" },
      { name: "ประทาย", zipCode: "30180" },
      { name: "ปักธงชัย", zipCode: "30150" },
      { name: "พิมาย", zipCode: "30110" },
      { name: "ห้วยแถลง", zipCode: "30240" },
      { name: "ชุมพวง", zipCode: "30270" },
      { name: "สูงเนิน", zipCode: "30170" },
      { name: "ขามทะเลสอ", zipCode: "30280" },
      { name: "สีคิ้ว", zipCode: "30140" },
      { name: "ปากช่อง", zipCode: "30130" },
      { name: "หนองบุญมาก", zipCode: "30410" },
      { name: "แก้งสนามนาง", zipCode: "30440" },
      { name: "โนนแดง", zipCode: "30360" },
      { name: "วังน้ำเขียว", zipCode: "30370" },
      { name: "เทพารักษ์", zipCode: "30210" },
      { name: "เมืองยาง", zipCode: "30270" },
      { name: "พระทองคำ", zipCode: "30220" },
      { name: "ลำทะเมนชัย", zipCode: "30270" },
      { name: "บัวลาย", zipCode: "30120" },
      { name: "สีดา", zipCode: "30430" },
      { name: "เฉลิมพระเกียรติ", zipCode: "30000" },
    ],
  },
  "บุรีรัมย์": {
    districts: [
      { name: "เมืองบุรีรัมย์", zipCode: "31000" },
      { name: "คูเมือง", zipCode: "31190" },
      { name: "กระสัง", zipCode: "31160" },
      { name: "นางรอง", zipCode: "31110" },
      { name: "หนองกี่", zipCode: "31210" },
      { name: "ละหานทราย", zipCode: "31170" },
      { name: "ประโคนชัย", zipCode: "31140" },
      { name: "บ้านกรวด", zipCode: "31180" },
      { name: "พุทไธสง", zipCode: "31120" },
      { name: "ลำปลายมาศ", zipCode: "31130" },
      { name: "สตึก", zipCode: "31150" },
      { name: "ปะคำ", zipCode: "31220" },
      { name: "นาโพธิ์", zipCode: "31230" },
      { name: "หนองหงส์", zipCode: "31240" },
      { name: "พลับพลาชัย", zipCode: "31250" },
      { name: "ห้วยราช", zipCode: "31000" },
      { name: "โนนสุวรรณ", zipCode: "31110" },
      { name: "ชำนิ", zipCode: "31110" },
      { name: "บ้านใหม่ไชยพจน์", zipCode: "31120" },
      { name: "โนนดินแดง", zipCode: "31260" },
      { name: "บ้านด่าน", zipCode: "31000" },
      { name: "แคนดง", zipCode: "31150" },
      { name: "เฉลิมพระเกียรติ", zipCode: "31110" },
    ],
  },
  "สุรินทร์": {
    districts: [
      { name: "เมืองสุรินทร์", zipCode: "32000" },
      { name: "ชุมพลบุรี", zipCode: "32190" },
      { name: "ท่าตูม", zipCode: "32120" },
      { name: "จอมพระ", zipCode: "32180" },
      { name: "ปราสาท", zipCode: "32140" },
      { name: "กาบเชิง", zipCode: "32210" },
      { name: "รัตนบุรี", zipCode: "32130" },
      { name: "สนม", zipCode: "32160" },
      { name: "ศีขรภูมิ", zipCode: "32110" },
      { name: "สังขะ", zipCode: "32150" },
      { name: "ลำดวน", zipCode: "32220" },
      { name: "สำโรงทาบ", zipCode: "32170" },
      { name: "บัวเชด", zipCode: "32230" },
      { name: "พนมดงรัก", zipCode: "32140" },
      { name: "ศรีณรงค์", zipCode: "32150" },
      { name: "เขวาสินรินทร์", zipCode: "32000" },
      { name: "โนนนารายณ์", zipCode: "32130" },
    ],
  },
  "ศรีสะเกษ": {
    districts: [
      { name: "เมืองศรีสะเกษ", zipCode: "33000" },
      { name: "ยางชุมน้อย", zipCode: "33190" },
      { name: "กันทรารมย์", zipCode: "33130" },
      { name: "กันทรลักษ์", zipCode: "33110" },
      { name: "ขุขันธ์", zipCode: "33140" },
      { name: "ไพรบึง", zipCode: "33180" },
      { name: "ปรางค์กู่", zipCode: "33170" },
      { name: "ขุนหาญ", zipCode: "33150" },
      { name: "ราษีไศล", zipCode: "33160" },
      { name: "อุทุมพรพิสัย", zipCode: "33120" },
      { name: "บึงบูรพ์", zipCode: "33220" },
      { name: "ห้วยทับทัน", zipCode: "33210" },
      { name: "โนนคูณ", zipCode: "33250" },
      { name: "ศรีรัตนะ", zipCode: "33240" },
      { name: "น้ำเกลี้ยง", zipCode: "33130" },
      { name: "วังหิน", zipCode: "33270" },
      { name: "ภูสิงห์", zipCode: "33140" },
      { name: "เมืองจันทร์", zipCode: "33120" },
      { name: "เบญจลักษ์", zipCode: "33110" },
      { name: "พยุห์", zipCode: "33230" },
      { name: "โพธิ์ศรีสุวรรณ", zipCode: "33120" },
      { name: "ศิลาลาด", zipCode: "33160" },
    ],
  },
  "อุบลราชธานี": {
    districts: [
      { name: "เมืองอุบลราชธานี", zipCode: "34000" },
      { name: "ศรีเมืองใหม่", zipCode: "34250" },
      { name: "โขงเจียม", zipCode: "34220" },
      { name: "เขื่องใน", zipCode: "34150" },
      { name: "เขมราฐ", zipCode: "34170" },
      { name: "เดชอุดม", zipCode: "34160" },
      { name: "นาจะหลวย", zipCode: "34280" },
      { name: "น้ำยืน", zipCode: "34260" },
      { name: "บุณฑริก", zipCode: "34230" },
      { name: "ตระการพืชผล", zipCode: "34130" },
      { name: "กุดข้าวปุ้น", zipCode: "34270" },
      { name: "ม่วงสามสิบ", zipCode: "34140" },
      { name: "วารินชำราบ", zipCode: "34190" },
      { name: "พิบูลมังสาหาร", zipCode: "34110" },
      { name: "ตาลสุม", zipCode: "34330" },
      { name: "โพธิ์ไทร", zipCode: "34340" },
      { name: "สำโรง", zipCode: "34360" },
      { name: "ดอนมดแดง", zipCode: "34000" },
      { name: "สิรินธร", zipCode: "34350" },
      { name: "ทุ่งศรีอุดม", zipCode: "34160" },
      { name: "นาเยีย", zipCode: "34160" },
      { name: "นาตาล", zipCode: "34170" },
      { name: "เหล่าเสือโก้ก", zipCode: "34000" },
      { name: "สว่างวีระวงศ์", zipCode: "34190" },
      { name: "น้ำขุ่น", zipCode: "34260" },
    ],
  },
  "ยโสธร": {
    districts: [
      { name: "เมืองยโสธร", zipCode: "35000" },
      { name: "ทรายมูล", zipCode: "35170" },
      { name: "กุดชุม", zipCode: "35140" },
      { name: "คำเขื่อนแก้ว", zipCode: "35110" },
      { name: "ป่าติ้ว", zipCode: "35150" },
      { name: "มหาชนะชัย", zipCode: "35130" },
      { name: "ค้อวัง", zipCode: "35160" },
      { name: "เลิงนกทา", zipCode: "35120" },
      { name: "ไทยเจริญ", zipCode: "35120" },
    ],
  },
  "อำนาจเจริญ": {
    districts: [
      { name: "เมืองอำนาจเจริญ", zipCode: "37000" },
      { name: "ชานุมาน", zipCode: "37210" },
      { name: "ปทุมราชวงศา", zipCode: "37110" },
      { name: "พนา", zipCode: "37180" },
      { name: "เสนางคนิคม", zipCode: "37290" },
      { name: "หัวตะพาน", zipCode: "37240" },
      { name: "ลืออำนาจ", zipCode: "37000" },
    ],
  },
  "มุกดาหาร": {
    districts: [
      { name: "เมืองมุกดาหาร", zipCode: "49000" },
      { name: "นิคมคำสร้อย", zipCode: "49130" },
      { name: "ดอนตาล", zipCode: "49120" },
      { name: "ดงหลวง", zipCode: "49140" },
      { name: "คำชะอี", zipCode: "49110" },
      { name: "หว้านใหญ่", zipCode: "49150" },
      { name: "หนองสูง", zipCode: "49160" },
    ],
  },
  "ร้อยเอ็ด": {
    districts: [
      { name: "เมืองร้อยเอ็ด", zipCode: "45000" },
      { name: "เกษตรวิสัย", zipCode: "45150" },
      { name: "ปทุมรัตต์", zipCode: "45190" },
      { name: "จตุรพักตรพิมาน", zipCode: "45180" },
      { name: "ธวัชบุรี", zipCode: "45170" },
      { name: "พนมไพร", zipCode: "45140" },
      { name: "โพนทอง", zipCode: "45110" },
      { name: "โพธิ์ชัย", zipCode: "45230" },
      { name: "หนองพอก", zipCode: "45210" },
      { name: "เสลภูมิ", zipCode: "45120" },
      { name: "สุวรรณภูมิ", zipCode: "45130" },
      { name: "อาจสามารถ", zipCode: "45160" },
      { name: "เมยวดี", zipCode: "45250" },
      { name: "ศรีสมเด็จ", zipCode: "45000" },
      { name: "จังหาร", zipCode: "45000" },
      { name: "เชียงขวัญ", zipCode: "45000" },
      { name: "หนองฮี", zipCode: "45140" },
      { name: "ทุ่งเขาหลวง", zipCode: "45170" },
      { name: "โพนทราย", zipCode: "45240" },
      { name: "ม่วงลาด", zipCode: "45170" },
    ],
  },
  "มหาสารคาม": {
    districts: [
      { name: "เมืองมหาสารคาม", zipCode: "44000" },
      { name: "แกดำ", zipCode: "44190" },
      { name: "โกสุมพิสัย", zipCode: "44140" },
      { name: "กันทรวิชัย", zipCode: "44150" },
      { name: "เชียงยืน", zipCode: "44160" },
      { name: "บรบือ", zipCode: "44130" },
      { name: "นาเชือก", zipCode: "44170" },
      { name: "พยัคฆภูมิพิสัย", zipCode: "44110" },
      { name: "วาปีปทุม", zipCode: "44120" },
      { name: "นาดูน", zipCode: "44180" },
      { name: "ยางสีสุราช", zipCode: "44210" },
      { name: "กุดรัง", zipCode: "44130" },
      { name: "ชื่นชม", zipCode: "44160" },
    ],
  },
  "กาฬสินธุ์": {
    districts: [
      { name: "เมืองกาฬสินธุ์", zipCode: "46000" },
      { name: "นามน", zipCode: "46230" },
      { name: "กมลาไสย", zipCode: "46130" },
      { name: "ร่องคำ", zipCode: "46210" },
      { name: "กุฉินารายณ์", zipCode: "46110" },
      { name: "เขาวง", zipCode: "46160" },
      { name: "ยางตลาด", zipCode: "46120" },
      { name: "ห้วยเม็ก", zipCode: "46170" },
      { name: "สหัสขันธ์", zipCode: "46140" },
      { name: "คำม่วง", zipCode: "46180" },
      { name: "ท่าคันโท", zipCode: "46190" },
      { name: "หนองกุงศรี", zipCode: "46220" },
      { name: "สมเด็จ", zipCode: "46150" },
      { name: "ห้วยผึ้ง", zipCode: "46240" },
      { name: "สามชัย", zipCode: "46180" },
      { name: "นาคู", zipCode: "46160" },
      { name: "ดอนจาน", zipCode: "46000" },
      { name: "ฆ้องชัย", zipCode: "46130" },
    ],
  },
  "สกลนคร": {
    districts: [
      { name: "เมืองสกลนคร", zipCode: "47000" },
      { name: "กุสุมาลย์", zipCode: "47210" },
      { name: "กุดบาก", zipCode: "47180" },
      { name: "พรรณานิคม", zipCode: "47130" },
      { name: "พังโคน", zipCode: "47160" },
      { name: "วาริชภูมิ", zipCode: "47150" },
      { name: "นิคมน้ำอูน", zipCode: "47270" },
      { name: "วานรนิวาส", zipCode: "47120" },
      { name: "คำตากล้า", zipCode: "47250" },
      { name: "บ้านม่วง", zipCode: "47140" },
      { name: "อากาศอำนวย", zipCode: "47170" },
      { name: "สว่างแดนดิน", zipCode: "47110" },
      { name: "ส่องดาว", zipCode: "47190" },
      { name: "เต่างอย", zipCode: "47260" },
      { name: "โคกศรีสุพรรณ", zipCode: "47280" },
      { name: "เจริญศิลป์", zipCode: "47290" },
      { name: "โพนนาแก้ว", zipCode: "47230" },
      { name: "ภูพาน", zipCode: "47180" },
    ],
  },
  "นครพนม": {
    districts: [
      { name: "เมืองนครพนม", zipCode: "48000" },
      { name: "ปลาปาก", zipCode: "48160" },
      { name: "ท่าอุเทน", zipCode: "48120" },
      { name: "บ้านแพง", zipCode: "48140" },
      { name: "ธาตุพนม", zipCode: "48110" },
      { name: "เรณูนคร", zipCode: "48170" },
      { name: "นาแก", zipCode: "48130" },
      { name: "ศรีสงคราม", zipCode: "48150" },
      { name: "นาหว้า", zipCode: "48180" },
      { name: "โพนสวรรค์", zipCode: "48190" },
      { name: "นาทม", zipCode: "48140" },
      { name: "วังยาง", zipCode: "48130" },
    ],
  },
  "หนองคาย": {
    districts: [
      { name: "เมืองหนองคาย", zipCode: "43000" },
      { name: "ท่าบ่อ", zipCode: "43110" },
      { name: "โพนพิสัย", zipCode: "43120" },
      { name: "ศรีเชียงใหม่", zipCode: "43130" },
      { name: "สังคม", zipCode: "43160" },
      { name: "สระใคร", zipCode: "43100" },
      { name: "เฝ้าไร่", zipCode: "43120" },
      { name: "รัตนวาปี", zipCode: "43120" },
      { name: "โพธิ์ตาก", zipCode: "43130" },
    ],
  },
  "บึงกาฬ": {
    districts: [
      { name: "เมืองบึงกาฬ", zipCode: "38000" },
      { name: "พรเจริญ", zipCode: "38180" },
      { name: "โซ่พิสัย", zipCode: "38170" },
      { name: "เซกา", zipCode: "38150" },
      { name: "ปากคาด", zipCode: "38190" },
      { name: "บึงโขงหลง", zipCode: "38220" },
      { name: "ศรีวิไล", zipCode: "38210" },
      { name: "บุ้งคล้า", zipCode: "38000" },
    ],
  },
  "เลย": {
    districts: [
      { name: "เมืองเลย", zipCode: "42000" },
      { name: "นาด้วง", zipCode: "42210" },
      { name: "เชียงคาน", zipCode: "42110" },
      { name: "ปากชม", zipCode: "42150" },
      { name: "ด่านซ้าย", zipCode: "42120" },
      { name: "นาแห้ว", zipCode: "42170" },
      { name: "ภูเรือ", zipCode: "42160" },
      { name: "ท่าลี่", zipCode: "42140" },
      { name: "วังสะพุง", zipCode: "42130" },
      { name: "ภูกระดึง", zipCode: "42180" },
      { name: "ภูหลวง", zipCode: "42230" },
      { name: "ผาขาว", zipCode: "42240" },
      { name: "เอราวัณ", zipCode: "42220" },
      { name: "หนองหิน", zipCode: "42190" },
    ],
  },
  "หนองบัวลำภู": {
    districts: [
      { name: "เมืองหนองบัวลำภู", zipCode: "39000" },
      { name: "นากลาง", zipCode: "39170" },
      { name: "โนนสัง", zipCode: "39140" },
      { name: "ศรีบุญเรือง", zipCode: "39180" },
      { name: "สุวรรณคูหา", zipCode: "39130" },
      { name: "นาวัง", zipCode: "39170" },
    ],
  },
  "อุดรธานี": {
    districts: [
      { name: "เมืองอุดรธานี", zipCode: "41000" },
      { name: "กุดจับ", zipCode: "41250" },
      { name: "หนองวัวซอ", zipCode: "41360" },
      { name: "กุมภวาปี", zipCode: "41110" },
      { name: "โนนสะอาด", zipCode: "41240" },
      { name: "หนองหาน", zipCode: "41130" },
      { name: "ทุ่งฝน", zipCode: "41310" },
      { name: "ไชยวาน", zipCode: "41290" },
      { name: "ศรีธาตุ", zipCode: "41230" },
      { name: "วังสามหมอ", zipCode: "41280" },
      { name: "บ้านดุง", zipCode: "41190" },
      { name: "บ้านผือ", zipCode: "41160" },
      { name: "น้ำโสม", zipCode: "41210" },
      { name: "เพ็ญ", zipCode: "41150" },
      { name: "สร้างคอม", zipCode: "41260" },
      { name: "หนองแสง", zipCode: "41340" },
      { name: "นายูง", zipCode: "41380" },
      { name: "พิบูลย์รักษ์", zipCode: "41130" },
      { name: "กู่แก้ว", zipCode: "41130" },
      { name: "ประจักษ์ศิลปาคม", zipCode: "41110" },
    ],
  },
  "ขอนแก่น": {
    districts: [
      { name: "เมืองขอนแก่น", zipCode: "40000" },
      { name: "บ้านฝาง", zipCode: "40270" },
      { name: "พระยืน", zipCode: "40320" },
      { name: "หนองเรือ", zipCode: "40210" },
      { name: "ชุมแพ", zipCode: "40130" },
      { name: "สีชมพู", zipCode: "40220" },
      { name: "น้ำพอง", zipCode: "40140" },
      { name: "อุบลรัตน์", zipCode: "40250" },
      { name: "กระนวน", zipCode: "40170" },
      { name: "บ้านไผ่", zipCode: "40110" },
      { name: "เปือยน้อย", zipCode: "40340" },
      { name: "พล", zipCode: "40120" },
      { name: "แวงใหญ่", zipCode: "40330" },
      { name: "แวงน้อย", zipCode: "40150" },
      { name: "หนองสองห้อง", zipCode: "40190" },
      { name: "ภูเวียง", zipCode: "40150" },
      { name: "มัญจาคีรี", zipCode: "40160" },
      { name: "ชนบท", zipCode: "40180" },
      { name: "เขาสวนกวาง", zipCode: "40280" },
      { name: "ภูผาม่าน", zipCode: "40350" },
      { name: "ซำสูง", zipCode: "40170" },
      { name: "โคกโพธิ์ไชย", zipCode: "40160" },
      { name: "หนองนาคำ", zipCode: "40150" },
      { name: "บ้านแฮด", zipCode: "40110" },
      { name: "โนนศิลา", zipCode: "40110" },
      { name: "เวียงเก่า", zipCode: "40150" },
    ],
  },
  "ชัยภูมิ": {
    districts: [
      { name: "เมืองชัยภูมิ", zipCode: "36000" },
      { name: "บ้านเขว้า", zipCode: "36170" },
      { name: "คอนสวรรค์", zipCode: "36140" },
      { name: "เกษตรสมบูรณ์", zipCode: "36120" },
      { name: "หนองบัวแดง", zipCode: "36210" },
      { name: "จัตุรัส", zipCode: "36130" },
      { name: "บำเหน็จณรงค์", zipCode: "36160" },
      { name: "หนองบัวระเหว", zipCode: "36250" },
      { name: "เทพสถิต", zipCode: "36230" },
      { name: "ภูเขียว", zipCode: "36110" },
      { name: "บ้านแท่น", zipCode: "36190" },
      { name: "แก้งคร้อ", zipCode: "36150" },
      { name: "คอนสาร", zipCode: "36180" },
      { name: "ภักดีชุมพล", zipCode: "36260" },
      { name: "เนินสง่า", zipCode: "36130" },
      { name: "ซับใหญ่", zipCode: "36130" },
    ],
  },
  "นครราชสีมา (โคราช)": {
    districts: [
      { name: "เมืองนครราชสีมา", zipCode: "30000" },
    ],
  },
  "สุราษฎร์ธานี": {
    districts: [
      { name: "เมืองสุราษฎร์ธานี", zipCode: "84000" },
      { name: "กาญจนดิษฐ์", zipCode: "84160" },
      { name: "ดอนสัก", zipCode: "84220" },
      { name: "เกาะสมุย", zipCode: "84140" },
      { name: "เกาะพะงัน", zipCode: "84280" },
      { name: "ไชยา", zipCode: "84110" },
      { name: "ท่าชนะ", zipCode: "84170" },
      { name: "คีรีรัฐนิคม", zipCode: "84180" },
      { name: "บ้านตาขุน", zipCode: "84230" },
      { name: "พนม", zipCode: "84250" },
      { name: "ท่าฉาง", zipCode: "84150" },
      { name: "บ้านนาสาร", zipCode: "84120" },
      { name: "บ้านนาเดิม", zipCode: "84240" },
      { name: "เคียนซา", zipCode: "84260" },
      { name: "เวียงสระ", zipCode: "84190" },
      { name: "พระแสง", zipCode: "84210" },
      { name: "พุนพิน", zipCode: "84130" },
      { name: "ชัยบุรี", zipCode: "84350" },
      { name: "วิภาวดี", zipCode: "84370" },
    ],
  },
  "นครศรีธรรมราช": {
    districts: [
      { name: "เมืองนครศรีธรรมราช", zipCode: "80000" },
      { name: "พรหมคีรี", zipCode: "80320" },
      { name: "ลานสกา", zipCode: "80230" },
      { name: "ฉวาง", zipCode: "80150" },
      { name: "พิปูน", zipCode: "80270" },
      { name: "เชียรใหญ่", zipCode: "80190" },
      { name: "ชะอวด", zipCode: "80180" },
      { name: "ท่าศาลา", zipCode: "80160" },
      { name: "ทุ่งสง", zipCode: "80110" },
      { name: "นาบอน", zipCode: "80220" },
      { name: "ทุ่งใหญ่", zipCode: "80240" },
      { name: "ปากพนัง", zipCode: "80140" },
      { name: "ร่อนพิบูลย์", zipCode: "80130" },
      { name: "สิชล", zipCode: "80120" },
      { name: "ขนอม", zipCode: "80210" },
      { name: "หัวไทร", zipCode: "80170" },
      { name: "บางขัน", zipCode: "80360" },
      { name: "ถ้ำพรรณรา", zipCode: "80260" },
      { name: "จุฬาภรณ์", zipCode: "80130" },
      { name: "พระพรหม", zipCode: "80000" },
      { name: "นบพิตำ", zipCode: "80160" },
      { name: "ช้างกลาง", zipCode: "80250" },
      { name: "เฉลิมพระเกียรติ", zipCode: "80190" },
    ],
  },
  "พัทลุง": {
    districts: [
      { name: "เมืองพัทลุง", zipCode: "93000" },
      { name: "กงหรา", zipCode: "93180" },
      { name: "เขาชัยสน", zipCode: "93130" },
      { name: "ตะโหมด", zipCode: "93160" },
      { name: "ควนขนุน", zipCode: "93110" },
      { name: "ปากพะยูน", zipCode: "93120" },
      { name: "ศรีบรรพต", zipCode: "93190" },
      { name: "ป่าบอน", zipCode: "93170" },
      { name: "บางแก้ว", zipCode: "93140" },
      { name: "ป่าพะยอม", zipCode: "93210" },
      { name: "ศรีนครินทร์", zipCode: "93000" },
    ],
  },
  "ตรัง": {
    districts: [
      { name: "เมืองตรัง", zipCode: "92000" },
      { name: "กันตัง", zipCode: "92110" },
      { name: "ย่านตาขาว", zipCode: "92140" },
      { name: "ปะเหลียน", zipCode: "92180" },
      { name: "สิเกา", zipCode: "92150" },
      { name: "ห้วยยอด", zipCode: "92130" },
      { name: "วังวิเศษ", zipCode: "92000" },
      { name: "นาโยง", zipCode: "92170" },
      { name: "รัษฎา", zipCode: "92160" },
      { name: "หาดสำราญ", zipCode: "92120" },
    ],
  },
  "สตูล": {
    districts: [
      { name: "เมืองสตูล", zipCode: "91000" },
      { name: "ควนโดน", zipCode: "91160" },
      { name: "ควนกาหลง", zipCode: "91130" },
      { name: "ท่าแพ", zipCode: "91150" },
      { name: "ละงู", zipCode: "91110" },
      { name: "ทุ่งหว้า", zipCode: "91120" },
      { name: "มะนัง", zipCode: "91130" },
    ],
  },
  "สงขลา": {
    districts: [
      { name: "เมืองสงขลา", zipCode: "90000" },
      { name: "สทิงพระ", zipCode: "90190" },
      { name: "จะนะ", zipCode: "90130" },
      { name: "นาทวี", zipCode: "90160" },
      { name: "เทพา", zipCode: "90150" },
      { name: "สะบ้าย้อย", zipCode: "90210" },
      { name: "ระโนด", zipCode: "90140" },
      { name: "กระแสสินธุ์", zipCode: "90270" },
      { name: "รัตภูมิ", zipCode: "90180" },
      { name: "สะเดา", zipCode: "90120" },
      { name: "หาดใหญ่", zipCode: "90110" },
      { name: "นาหม่อม", zipCode: "90310" },
      { name: "ควนเนียง", zipCode: "90220" },
      { name: "บางกล่ำ", zipCode: "90110" },
      { name: "สิงหนคร", zipCode: "90280" },
      { name: "คลองหอยโข่ง", zipCode: "90115" },
    ],
  },
  "ปัตตานี": {
    districts: [
      { name: "เมืองปัตตานี", zipCode: "94000" },
      { name: "โคกโพธิ์", zipCode: "94180" },
      { name: "หนองจิก", zipCode: "94170" },
      { name: "ปะนาเระ", zipCode: "94130" },
      { name: "มายอ", zipCode: "94140" },
      { name: "ทุ่งยางแดง", zipCode: "94140" },
      { name: "สายบุรี", zipCode: "94110" },
      { name: "ไม้แก่น", zipCode: "94220" },
      { name: "ยะหริ่ง", zipCode: "94150" },
      { name: "ยะรัง", zipCode: "94160" },
      { name: "กะพ้อ", zipCode: "94230" },
      { name: "แม่ลาน", zipCode: "94180" },
    ],
  },
  "ยะลา": {
    districts: [
      { name: "เมืองยะลา", zipCode: "95000" },
      { name: "เบตง", zipCode: "95110" },
      { name: "บันนังสตา", zipCode: "95130" },
      { name: "ธารโต", zipCode: "95150" },
      { name: "ยะหา", zipCode: "95120" },
      { name: "รามัน", zipCode: "95140" },
      { name: "กาบัง", zipCode: "95120" },
      { name: "กรงปินัง", zipCode: "95000" },
    ],
  },
  "นราธิวาส": {
    districts: [
      { name: "เมืองนราธิวาส", zipCode: "96000" },
      { name: "ตากใบ", zipCode: "96110" },
      { name: "บาเจาะ", zipCode: "96170" },
      { name: "ยี่งอ", zipCode: "96180" },
      { name: "ระแงะ", zipCode: "96130" },
      { name: "รือเสาะ", zipCode: "96150" },
      { name: "ศรีสาคร", zipCode: "96210" },
      { name: "แว้ง", zipCode: "96160" },
      { name: "สุคิริน", zipCode: "96190" },
      { name: "สุไหงโก-ลก", zipCode: "96120" },
      { name: "สุไหงปาดี", zipCode: "96140" },
      { name: "จะแนะ", zipCode: "96220" },
      { name: "เจาะไอร้อง", zipCode: "96130" },
    ],
  },
  "ภูเก็ต": {
    districts: [
      { name: "เมืองภูเก็ต", zipCode: "83000" },
      { name: "กะทู้", zipCode: "83120" },
      { name: "ถลาง", zipCode: "83110" },
    ],
  },
  "กระบี่": {
    districts: [
      { name: "เมืองกระบี่", zipCode: "81000" },
      { name: "เขาพนม", zipCode: "81140" },
      { name: "เกาะลันตา", zipCode: "81150" },
      { name: "คลองท่อม", zipCode: "81120" },
      { name: "อ่าวลึก", zipCode: "81110" },
      { name: "ปลายพระยา", zipCode: "81160" },
      { name: "ลำทับ", zipCode: "81190" },
      { name: "เหนือคลอง", zipCode: "81130" },
    ],
  },
  "พังงา": {
    districts: [
      { name: "เมืองพังงา", zipCode: "82000" },
      { name: "เกาะยาว", zipCode: "82160" },
      { name: "กะปง", zipCode: "82170" },
      { name: "ตะกั่วทุ่ง", zipCode: "82130" },
      { name: "ตะกั่วป่า", zipCode: "82110" },
      { name: "คุระบุรี", zipCode: "82150" },
      { name: "ทับปุด", zipCode: "82180" },
      { name: "ท้ายเหมือง", zipCode: "82120" },
    ],
  },
  "ระนอง": {
    districts: [
      { name: "เมืองระนอง", zipCode: "85000" },
      { name: "ละอุ่น", zipCode: "85130" },
      { name: "กะเปอร์", zipCode: "85120" },
      { name: "กระบุรี", zipCode: "85110" },
      { name: "สุขสำราญ", zipCode: "85120" },
    ],
  },
  "ชุมพร": {
    districts: [
      { name: "เมืองชุมพร", zipCode: "86000" },
      { name: "ท่าแซะ", zipCode: "86140" },
      { name: "ปะทิว", zipCode: "86160" },
      { name: "หลังสวน", zipCode: "86110" },
      { name: "ละแม", zipCode: "86170" },
      { name: "พะโต๊ะ", zipCode: "86180" },
      { name: "สวี", zipCode: "86130" },
      { name: "ทุ่งตะโก", zipCode: "86220" },
    ],
  },
}

export const PROVINCES = Object.keys(THAILAND_ADDRESS).sort()

export function getDistricts(province: string): District[] {
  return THAILAND_ADDRESS[province]?.districts ?? []
}

export function getZipCodes(province: string, district: string): string[] {
  const found = getDistricts(province).find(d => d.name === district)
  return found ? [found.zipCode] : []
}
